name: Build WinUI3 App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SOLUTION_FILE_PATH: HelloWorldApp.sln
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Restore NuGet packages
      run: |
        nuget restore ${{ env.SOLUTION_FILE_PATH }} -ConfigFile nuget.config
        msbuild ${{ env.SOLUTION_FILE_PATH }} /t:Restore /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=${{ env.BUILD_PLATFORM }}

    - name: Decode the certificate
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.BASE64_ENCODED_PFX }}")
        $certificatePath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "GitHubActionsWorkflow.pfx"
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

    - name: Build the solution
      run: |
        msbuild ${{ env.SOLUTION_FILE_PATH }} `
          /p:Configuration=${{ env.BUILD_CONFIGURATION }} `
          /p:Platform=${{ env.BUILD_PLATFORM }} `
          /p:AppxBundlePlatforms=${{ env.BUILD_PLATFORM }} `
          /p:AppxPackageDir="${{ github.workspace }}\AppPackages\" `
          /p:AppxBundle=Never `
          /p:UapAppxPackageBuildMode=SideloadOnly `
          /p:AppxPackageSigningEnabled=true `
          /p:PackageCertificateKeyFile="${{ github.workspace }}\GitHubActionsWorkflow.pfx" `
          /p:PackageCertificatePassword="${{ secrets.PFX_PASSWORD }}"

    - name: Remove the certificate
      run: Remove-Item -path "${{ github.workspace }}\GitHubActionsWorkflow.pfx"
      if: always()

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MSIX Package
        path: ${{ github.workspace }}\AppPackages\**\*.msix